const mockProducts = [
  {
    id: 1,
    name: "Canon Camera EOS 2000, Black 10x zoom",
    brand: "Canon",
    features: ["10x zoom", "Digital SLR"],
    condition: "new",
    price: 998.00,
    oldPrice: 1326.00,
    rating: 4.5,
    reviews: 154,
    freeShipping: true,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    image: "/assets/images/p16.png",
    category: "Cameras",
    isNew: true
  },
  {
    id: 2,
    name: "GoPro HERO6 4K Action Camera - Black",
    brand: "GoPro",
    features: ["4K Video", "Waterproof"],
    condition: "new",
    price: 998.00,
    oldPrice: null,
    rating: 4.2,
    reviews: 87,
    freeShipping: true,
    description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "/assets/images/product-view-2.png",
    category: "Action Cameras"
  },
  {
    id: 3,
    name: "Sony Alpha a7 III Mirrorless Microphone",
    brand: "Sony",
    features: ["Full Frame", "Image Stabilization"],
    condition: "refurbished",
    price: 520.00,
    oldPrice: 680.00,
    rating: 4.8,
    reviews: 213,
    freeShipping: true,
    description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    image: "/assets/images/product-4.png",
    category: "Mirrorless"
  },
  {
    id: 4,
    name: "Nikon D850 DSLR Camera",
    brand: "Nikon",
    features: ["High Resolution", "DSLR"],
    condition: "old",
    price: 899.00,
    oldPrice: 999.00,
    rating: 4.7,
    reviews: 189,
    freeShipping: true,
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "/assets/images/pr2.jpg",
    category: "DSLR"
  },
  {
    id: 5,
    name: "Fujifilm X-T4 Mirrorless Camera",
    brand: "Fujifilm",
    features: ["Video Features", "Compact"],
    condition: "new",
    price: 699.00,
    oldPrice: null,
    rating: 4.6,
    reviews: 142,
    freeShipping: true,
    description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    image: "/assets/images/product-3.png",
    category: "Mirrorless"
  },
  {
    id: 6,
    name: "Panasonic Lumix GH5",
    brand: "Panasonic",
    features: ["Micro Four Thirds", "Video Focus"],
    condition: "new",
    price: 1399.00,
    oldPrice: 1599.00,
    rating: 4.4,
    reviews: 98,
    freeShipping: false,
    description: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
    image: "/assets/images/pr5.jpg",
    category: "Mirrorless"
  },
  {
    id: 7,
    name: "Olympus OM-D E-M1 Mark III",
    brand: "Olympus",
    features: ["Weather Sealed", "Portable"],
    condition: "refurbished",
    price: 1799.00,
    oldPrice: null,
    rating: 4.3,
    reviews: 76,
    freeShipping: true,
    description: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur.",
    image: "/assets/images/product-2.png",
    category: "Mirrorless"
  },
  {
    id: 8,
    name: "Canon EOS R5 Mirrorless Camera",
    brand: "Canon",
    features: ["8K Video", "Full Frame"],
    condition: "new",
    price: 999.00,
    oldPrice: 1099.00,
    rating: 4.9,
    reviews: 267,
    freeShipping: true,
    description: "Adipisci velit, sed quia non numquam eius modi tempora incididunt ut labore et dolore magnam aliquam quaerat voluptatem.",
    image: "/assets/images/pr6.jpg",
    category: "Mirrorless"
  }
];

export default mockProducts;